# 在 MongoDB 服務中加入初始化腳本
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: web_ui
      MONGO_INITDB_ROOT_PASSWORD: hod2iddfsgsrl
      MONGO_INITDB_DATABASE: web_db
    volumes:
      - mongodb_data:/data/db
      - ./mongoDB_init/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    command: mongod --auth
    networks:
      - app_network

  flask_frontend:
    # ... 其他配置 ...
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_USERNAME: web_ui
      MONGODB_PASSWORD: hod2iddfsgsrl
    depends_on:
      - mongodb

  analysis_service:
    # ... 其他配置 ...
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_USERNAME: web_ui
      MONGODB_PASSWORD: hod2iddfsgsrl
    depends_on:
      - mongodb

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge